[package]
name = "slimp"
version = "0.1.0"
authors = ["Simon Mikkelsen <simonbodall@runbox.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
minreq = "2.3.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
